//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ITTSportsCarnivalApp.DBO;
using System.Data.Entity;

public partial class DataBaseContext : DbContext
{
    public DataBaseContext()
        : base("name=DataBaseContext")
    {
    }
    public virtual DbSet<Team> Team { get; set; }
    public virtual DbSet<Player> Player { get; set; }
    public virtual DbSet<Occasion> Occasion { get; set; }
    public virtual DbSet<Match> Match { get; set; }
    public virtual DbSet<GameType> GameType { get; set; }
    public virtual DbSet<Team_Player> Team_Player { get; set; }
}
