//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITTSportsCarnivalApp.DBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Player
    {
        public int id { get; set; }
        public int playerId { get; set; }
        public int teamId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
